language: java
jdk:
  - openjdk8

all_branches: true

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

notifications:
  email: false

dist: xenial

sudo: required

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7
    packages:
      - mysql-server

before_script:
  - mysql -u root -e "SET PASSWORD FOR root@localhost = PASSWORD('root');"
  - mysql -e 'create database fake_issues_test;'

# gradle test task
script:
  - ./gradlew test

