language: java
jdk:
  - openjdk8

all_branches: true

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

notifications:
  email: false

# Build (Build시 자동으로 test 수행)
script:
  # - cp ./src/main/resources/dev.application.properties ./src/main/resources/application.properties
  - ./gradlew test

