language: java
jdk:
  - openjdk8

all_branches: true

# branches:
#   only:
#     - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/demo/.m2/repository'
    - '$HOME/demo/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./demo/gradlew clean build"
