version: '3'
services:
  fake_issue:
    build:
      context: ./gradle
      args:
        - UID=70000
        - GID=70000
        - UNAME=vagrant1
    container_name: 'fake_issue'
    working_dir: '/home/vagrant1/opt'
    volumes:
      - ./works:/home/vagrant1/opt
    tty: true
    links:
      - mysql

  mysql:
    build:
      context: ./mysql57
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: 'mysql57'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./works/data/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always