version: '3'
services:
  dynamic_uid_image:
    build:
      context: .
      args:
        - UID=1000
        - GID=1000
        - UNAME=vagrant
    container_name: 'dynamic_uid_image'
    working_dir: '/home/vagrant'
    volumes:
      - ./works:/home/vagrant/.gradle
    tty: true