/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;


public class CalculatorTest {

    @Test
    public void test1(){
        //given
        long num1 = 1;
        long num2 = 2;

        //when
        long sum = num1 + num2;

        //thwn
        assertThat(sum).isEqualTo(3);
    }
}
