/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

import org.junit.Assert;

public class CalculatorTest {

    @Test
    public void test1(){
        //given
        long num1 = 1;
        long num2 = 2;

        //when
        long sum = num1 + num2;

        //thwn
        Assert.assertEquals(sum, 3);
    }
}
