CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NULL DEFAULT NULL,
  name VARCHAR(20) NULL DEFAULT NULL,
  password VARCHAR(500) NULL DEFAULT NULL,
  isAccountNonExpired TINYINT(1) NULL DEFAULT NULL,
  isAccountNonLocked TINYINT(1) NULL DEFAULT NULL,
  isCredentialsNonExpired TINYINT(1) NULL DEFAULT NULL,
  isEnabled TINYINT(1) NULL DEFAULT NULL
);

CREATE TABLE authority (
  username VARCHAR(20) NULL DEFAULT NULL,
  authority_name VARCHAR(20) NULL DEFAULT NULL
);

CREATE TABLE issues (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NULL DEFAULT NULL,
  content VARCHAR(255) NULL DEFAULT NULL,
  userId INT NULL DEFAULT NULL
);
